src/Entity/YtChannels.php
<?php

namespace App\Entity;

use App\Repository\YtChannelsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: YtChannelsRepository::class)]
class YtChannels
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $chan_id;

    #[ORM\Column(type: 'string', length: 255)]
    private $thumb;

    #[ORM\Column(type: 'string', length: 255)]
    private $chan_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $upload_playlist;

    #[ORM\Column(type: 'text')]
    private $chan_description;

    #[ORM\OneToMany(mappedBy: 'channel', targetEntity: YtVideos::class)]
    private $ytVideos;

    #[ORM\ManyToOne(targetEntity: YtCategories::class, inversedBy: 'ytChannels')]
    private $category;

    public function __construct()
    {
        $this->ytVideos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChanId(): ?string
    {
        return $this->chan_id;
    }

    public function setChanId(string $chan_id): self
    {
        $this->chan_id = $chan_id;

        return $this;
    }

    public function getThumb(): ?string
    {
        return $this->thumb;
    }

    public function setThumb(string $thumb): self
    {
        $this->thumb = $thumb;

        return $this;
    }

    public function getChanName(): ?string
    {
        return $this->chan_name;
    }

    public function setChanName(string $chan_name): self
    {
        $this->chan_name = $chan_name;

        return $this;
    }

    public function getUploadPlaylist(): ?string
    {
        return $this->upload_playlist;
    }

    public function setUploadPlaylist(string $upload_playlist): self
    {
        $this->upload_playlist = $upload_playlist;

        return $this;
    }

    public function getChanDescription(): ?string
    {
        return $this->chan_description;
    }

    public function setChanDescription(string $chan_description): self
    {
        $this->chan_description = $chan_description;

        return $this;
    }

    /**
     * @return Collection<int, YtVideos>
     */
    public function getYtVideos(): Collection
    {
        return $this->ytVideos;
    }

    public function addYtVideo(YtVideos $ytVideo): self
    {
        if (!$this->ytVideos->contains($ytVideo)) {
            $this->ytVideos[] = $ytVideo;
            $ytVideo->setChannel($this);
        }

        return $this;
    }

    public function removeYtVideo(YtVideos $ytVideo): self
    {
        if ($this->ytVideos->removeElement($ytVideo)) {
            // set the owning side to null (unless already changed)
            if ($ytVideo->getChannel() === $this) {
                $ytVideo->setChannel(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?YtCategories
    {
        return $this->category;
    }

    public function setCategory(?YtCategories $category): self
    {
        $this->category = $category;

        return $this;
    }
}

templates/admin_message.html.twig
{% extends '@!EasyAdmin/default/layout.html.twig' %}

{% block main %}
    <h1>{{ body_header }}</h1>
    <p>{{ body_message|raw }}</p>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/cv.html.twig
{% extends 'home.html.twig' %}
{% block banner %}
    <header id="header" >
        <h1><a href="/">Lukasz Andrzejak - Meltir</a></h1>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>
{% endblock %}

{% block main_body %}
    <header>
        <div class="inner">
            <h2>Curriculum Vitae</h2>
            <p>Current as of June 2019, please try <a href="https://www.linkedin.com/in/meltir" target="_blank">linkedin</a> for the most recent version</p>
            <p>The past few weeks were spent catching up with symfony flex and docker</p>
        </div>
    </header>
    <div class="wrapper">
        <div class="inner">
            {% for item in posts %}
                <h3 class="major">{{ item.title }}</h3>
                {{ item.body|raw }}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/empty_base.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ dump(posts) }}
{% endblock %}

templates/gallery.html.twig
{% extends 'solidstate/solidstate-base.html.twig' %}
{% set style_id=2 %}
{% block banner %}
    <header id="header" >
        <h1><a href="/">Lukasz Andrzejak - Meltir</a></h1>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>
{% endblock %}
{% block main_body %}
    <header>
        <div class="inner">
            <h2>Website gallery</h2>
            <p>Some of the websites I have worked on over the years</p>
            <p>Most are gone or upgraded by now, but a few are still kicking around</p>
            <p>Some I implemented the designs on, I worked on the backends for all of them, and designed only <b>one</b> of them (no points for guessing which one)</p>
        </div>
    </header>
    {% for gallery in galleries %}
        {% set style_id = style_id+1 %}
        {% if style_id > 6 %}
            {% set style_id=1 %}
        {% endif %}
        <section id="{{ random(100) }}" class="wrapper {{ cycle(['','alt'],style_id) }} style{{ style_id }}">
            <div class="inner">
                <h2 class="major">{{ gallery.title }}</h2>
                <p>{{ gallery.body|raw }}</p>
                <section class="features">
                    {% for gallery_item in gallery.pagePosts %}
                        {% set item = {
                            'linkImage': asset(postimagepath ~ gallery_item.linkImage),
                            'title': gallery_item.title,
                            'linkUrl': gallery_item.linkUrl,
                            'linkTitle': gallery_item.linkTitle,
                            'body': gallery_item.body }
                        %}
                        {% include 'solidstate/gallery-item.html.twig' with {'item': item} %}
                    {% endfor %}
                </section>
            </div>
        </section>
    {% endfor %}
{% endblock %}

templates/home.html.twig
{% extends 'solidstate/solidstate-base.html.twig' %}
{% block banner %}
<section id="banner">
    <div class="inner">
        <div class="logo"><img src="{{ asset('images/demon-circle.svg') }}" alt="My avatar since 2003"></div>
        <h2>Lukasz Andrzejak - Meltir</h2>
        <p>Senior PHP Developer</p>
        <p>Welcome to my personal website, I hope you like it</p>
    </div>
</section>
{% endblock %}
{% block main_body %}
    {% include 'solidstate/wide-block.html.twig' with {'wideblocks': posts} %}
{% endblock %}

templates/imdb.html.twig
{% extends 'solidstate/solidstate-base.html.twig' %}
{% block banner %}
    <header id="header" >
        <h1><a href="/">Lukasz Andrzejak - Meltir</a></h1>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>
{% endblock %}
{% block sourcecode %}<li class="fa-code"><a href="https://github.com/meltir/2019.meltir.com/blob/master/src/Meltir/imdb.php" target="_blank">Page source</a></li>{% endblock %}
{% block main_body %}
    <header>
        <div class="inner">
            <h2>My movie ratings</h2>
            <p>Movies I watched and liked (or disliked) enough to rate</p>
            <p>Also an example of a web scraper wrapper for a non-api integration</p>
            <p>If you want to do something like this, seek permission from IMDB</p>
        </div>
    </header>
    <section id="movies" class="wrapper alt style1">
        <div class="inner">
            <p>My generall rule of thumb is <5 avoid, 5 OK, >5 worth it for one reason or another.</p>
            <p>Some of these have a high rating because they are fun, some are well made, some make me reconsider my life choices, some because they are beautiful to watch.</p>
            <p>Best and most recent ones are listed first !</p>
            <section class="features">
                {% for movie in movies %}
                    {% set body %}
                        Released in  {{  movie.year|date('Y') }}, my rating <b>{{  movie.myRating }}</b>/10.</p>
                        <p>Synopsis: <br />{{ movie.synopsis }}
                    {% endset %}
                    {% set item = {
                        'linkImage': movie.poster,
                        'title': movie.title,
                        'linkUrl': movie.imdbLink,
                        'linkTitle': 'Movie details',
                        'body': body
                        }
                    %}

                    {% include 'solidstate/gallery-item.html.twig'  with item %}
                {% endfor %}
            </section>
        </div>
    </section>
    {% set style_id = 2 %}
    {{ include('solidstate/paginator.html.twig',{'page':paginator.page,'pages':paginator.pages,'base_route':paginator.base_route,'route_params':{}}) }}
    {% block pagination %}{% endblock %}
{% endblock %}

templates/thoughts.html.twig
{% extends 'home.html.twig' %}
{% block banner %}
    <header id="header" >
        <h1><a href="/">Lukasz Andrzejak - Meltir</a></h1>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>
{% endblock %}
{% block main_body %}
    <header>
        <div class="inner">
            <h2>Ramblings on tools and other thoughts</h2>
            <p>None of the below is gospel.<i>These are, like, my opinions, man</i></p>
            <p>Don’t take this page too seriously, there are jokes and other slightly cheeky bits on it</p>
            <p>I employ the practices of <a href="https://en.wikipedia.org/wiki/KISS_principle" target="_blank">KISS</a> and <a href="https://en.wikipedia.org/wiki/Don%27t_repeat_yourself" target="_blank">DRY</a> pretty much everywhere I can. Google them.</p>
            <p>Or click the links. Who am I to tell you what to do?</p>
            <p>This page should give you an idea of what my approach to development is</p>
        </div>
    </header>
    <div class="wrapper">
        <div class="inner">
            {% for item in posts %}
                <h3 class="major">{{ item.title }}</h3>
                {{ item.body|raw }}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/youtube.html.twig
{% extends 'solidstate/solidstate-base.html.twig' %}
{% block banner %}
    <header id="header" >
        <h1><a href="/">Lukasz Andrzejak - Meltir</a></h1>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>
{% endblock %}
{% block sourcecode %}<li class="fa-code"><a href="https://github.com/meltir/2019.meltir.com/blob/master/src/Meltir/youtube.php" target="_blank">Page source</a></li>{% endblock %}
{% block main_body %}
    <header>
        <div class="inner">
            <h2>My youtube feed</h2>
            <p>This is how I spend my leisure time</p>
            <p>This is also how I handle pagination, ajax, and third party integrations using existing libraries</p>
        </div>
    </header>
    <section class="wrapper spotlight alt style1">
        <div class="inner">
            <div class="content">
                <h2 class="major">Channel categories</h2>
                <p>Well, there are too many here to simply list them all. It would be chaos.</p>
                <p>So, I grouped them a bit. It has the side effect of making the logic slightly more interesting.</p>
                <ul class="actions fit small">
                    {% for category in categories %}
                        {% set route = path('app_youtube',{'slug': category.slug}) %}
                        {% set current_cat = (category == current_category) ? true : false %}
                        <li><a {{ (not current_cat) ? 'href=' ~ route }} class="button fit small {{ current_cat ? 'primary' }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
    {% set style_id=1 %}
    {% for channel in channels %}
        {% set style_id = style_id+1 %}
        {% if style_id > 6 %}
            {% set style_id=1 %}
        {% endif %}
        <section class="wrapper spotlight {{ cycle(['','alt'],style_id) }} style{{ style_id }}">
            <div class="inner">
                <a class="image"><img src="{{ channel.thumb }}" alt="{{ channel.chanName }}" /></a>
                <div class="content">
                    <h2 class="major">{{ channel.chanName }}</h2>
                    <p>{{ channel.chanDescription|slice(0,200) ~ '...' }}</p>
                    <a href="https://www.youtube.com/channel/{{ channel.chanId }}" class="special" target="_blank">View channel</a>
                </div>
            </div>
            <div class="inner" id="videos_{{ channel.chanId }}">
                {{ include('youtube_videos.html.twig',{'videos':videos[channel.id]}) }}
            </div>
            <div class="inner">
                <ul class="actions fit">
                    <li><a class="button videolist_prev disabled" page="1" chanid="{{ channel.chanId }}">Prev</a></li>
                    <li><a class="button videolist_next" page="2" chanid="{{ channel.chanId }}">Next</a></li>
                </ul>
            </div>
        </section>
    {% endfor %}
    {% set style_id = style_id +1 %}
    {{ include('solidstate/paginator.html.twig',{'page':paginator.page,'pages':paginator.pages,'base_route':paginator.base_route,'route_params':{'slug':current_category.slug}}) }}
    {% block pagination %}{% endblock %}
{% endblock %}

templates/youtube_videos.html.twig
<section class="features">
    {% for video in videos %}
        {% set item = {
            'linkImage': video.thumb,
            'title': video.title,
            'linkUrl': 'https://www.youtube.com/watch?v=' ~ video.videoid,
            'linkTitle': 'View video',
            'body': 'Published on ' ~ video.datePublished|date('j-n-Y') }
        %}
        {% include 'solidstate/gallery-item.html.twig'  with item %}
    {% endfor %}
</section>