src/Entity/PagePost.php
<?php

namespace App\Entity;

use App\Repository\PagePostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: PagePostRepository::class)]
class PagePost
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $body;

    #[Gedmo\SortablePosition]
    #[ORM\Column(type: 'integer', nullable: true)]
    private $post_order;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $active;

    #[Gedmo\SortableGroup]
    #[ORM\Column(type: 'string', length: 255)]
    private $page;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $link_image;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $link_url;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $link_title;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $title;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'pagePosts')]
    private $parent_post;

    #[ORM\OneToMany(mappedBy: 'parent_post', targetEntity: self::class)]
    private $pagePosts;

    public function __construct()
    {
        $this->pagePosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPostOrder(): ?int
    {
        return $this->post_order;
    }

    public function setPostOrder(?int $post_order): self
    {
        $this->post_order = $post_order;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getPage(): ?string
    {
        return $this->page;
    }

    public function setPage(string $page): self
    {
        $this->page = $page;

        return $this;
    }

    public function getLinkImage(): ?string
    {
        return $this->link_image;
    }

    public function setLinkImage(?string $link_image): self
    {
        $this->link_image = $link_image;

        return $this;
    }

    public function getLinkUrl(): ?string
    {
        return $this->link_url;
    }

    public function setLinkUrl(?string $link_url): self
    {
        $this->link_url = $link_url;

        return $this;
    }

    public function getLinkTitle(): ?string
    {
        return $this->link_title;
    }

    public function setLinkTitle(?string $link_title): self
    {
        $this->link_title = $link_title;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getParentPost(): ?self
    {
        return $this->parent_post;
    }

    public function setParentPost(?self $parent_post): self
    {
        $this->parent_post = $parent_post;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getPagePosts(): Collection
    {
        return $this->pagePosts;
    }

    public function addPagePost(self $pagePost): self
    {
        if (!$this->pagePosts->contains($pagePost)) {
            $this->pagePosts[] = $pagePost;
            $pagePost->setParentPost($this);
        }

        return $this;
    }

    public function removePagePost(self $pagePost): self
    {
        if ($this->pagePosts->removeElement($pagePost)) {
            // set the owning side to null (unless already changed)
            if ($pagePost->getParentPost() === $this) {
                $pagePost->setParentPost(null);
            }
        }

        return $this;
    }
}

templates/solidstate/gallery-item.html.twig
<article>
    <a class="image_feature" ><img src="{{ item.linkImage }}" alt="{{ item.title }}" /></a>
    <h3 class="major">{{ item.title }}</h3>
    <p>{{ item.body|raw }}</p>
    {% if item.linkUrl is not empty %}
    <a href="{{ item.linkUrl }}" class="special" target="_blank">{{ item.linkTitle }}</a>
    {% endif %}
</article>

templates/solidstate/gallery.html.twig
<section id="gallery{{ random('1000') }}" class="wrapper alt style1">
    <div class="inner">
        <h2 class="major">{{ gallery.title }}</h2>
        <p>{{ gallery.descriptions }}</p>
        <section class="features">
            {% for item in gallery.items %}
                {{ include 'gallery-item.html.twig' with 'gallery': item}) }}
            {% endfor %}
        </section>

        <ul class="actions">
            <li><a href="#" class="button">Browse All</a></li>
        </ul>
    </div>
</section>

templates/solidstate/paginator.html.twig
{#
page -- current page
pages -- how many pages are there
base_route -- base route to which a 'page' param is passed
max_pages how many pages to display at once as a maximum - set to an odd number so that current page is in the middle

#}
{% set max_pages = 9 %}
{% set surround_pages = max_pages // 2 %}
{% if ((page - surround_pages) <= 0) %}
    {% set start_page = 1 %}
{% else %}
    {% set start_page = page - surround_pages %}
{% endif %}
{% if ((page + surround_pages) <= pages) %}
    {% set end_page = max(page + surround_pages,max_pages) %}
{% else %}
    {% set end_page = pages %}
    {% set start_page = pages - max_pages + 1 %}
{% endif %}

{% if end_page > pages %}
    {% set end_page = pages %}
{% endif %}
{% if start_page < 1 %}
    {% set start_page = 1 %}
{% endif %}

{% if pages > 1 %}
    {% block pagination %}
    <section id="pagination" class="wrapper spotlight {{ cycle(['','alt'],style_id) }} style{{ style_id }}">
        <div class="inner">
            <div class="content">
                <ul class="pagination">
                    {% if page == 1 %}
                        <li><span class="button small disabled">Prev</span></li>
                    {% else %}
                        <li><a href="{{ path(base_route,{'page':page-1}|merge(route_params)) }}" class="button small">Prev</a></li>
                    {% endif %}
                    {% for i in start_page..end_page %}
                        {% if i == page %}
                            <li><a class="page active">{{ i }}</a></li>
                        {% else %}
                            <li><a href="{{ path(base_route,{'page':i}|merge(route_params)) }}" class="page">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page == pages %}
                        <li><span class="button small disabled">Next</span></li>
                    {% else %}
                        <li><a href="{{ path(base_route,{'page':page+1}|merge(route_params)) }}" class="button small">Next</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </section>
    {% endblock %}
{% endif %}

templates/solidstate/solidstate-base.html.twig
<!DOCTYPE HTML>
<!--
	Solid State by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>Lukasz Andrzejak @ Meltir</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}" />
    <link rel="icon" type="image/png" href="{{ asset('images/demon-circle.png') }}" />
    <noscript><link rel="stylesheet" href="{{ asset('assets/css/noscript.css') }}" /></noscript>
    {% block stylesheets %}{% endblock %}
</head>
<body class="is-preload">

<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Header -->
    {% block header %}
    <header id="header" class="alt">
        <h1><a href="/">Lukasz Andrzejak - Meltir</a></h1>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>
    {% endblock %}
{#
{'path':'youtube_list','title':'My youtube'},
{'path':'imdb_list','title':'My IMDB'},
#}
{% set menuitems = [
    {'path':'app_home','title':'Home'},
    {'path':'app_gallery','title':'Projects gallery'},
    {'path':'app_cv','title':'CV'},
    {'path':'app_youtube','title':'My Youtube'}
] %}
    <!-- Menu -->
    <nav id="menu">
        <div class="inner">
            <h2>Menu</h2>
            <ul class="links">
                {% for menu in menuitems %}
                    <li><a href="{{ path(menu.path) }}" title="{{ menu.title }}">{{ menu.title }}</a></li>
                {% endfor %}
            </ul>
            <a href="#" class="close">Close</a>
        </div>
    </nav>

    <!-- Banner -->
    {% block banner %}

    {% endblock %}

    <!-- Wrapper -->
    <section id="wrapper">
        {% block main_body %}
        {% endblock %}
    </section>

    <!-- Footer -->
    <section id="footer">
        <div class="inner">
            <h2 class="major">Get in touch</h2>
            <p>If you are looking to expand your team, like something I list here - get in touch on <a href="https://www.linkedin.com/in/meltir" target="_blank">LinkedIn</a> !</p>
            <ul class="contact">
                <li class="fa-home">Somewhere in North West London</li>
                <li class="fa-facebook"><a href="https://www.facebook.com/meltir" target="_blank">facebook.com/meltir</a></li>
                <li class="fa-linkedin"><a href="https://www.linkedin.com/in/meltir" target="_blank">linkedin.com/in/meltir</a></li>
                <li class="fa-github"><a href="https://github.com/meltir" target="_blank">github.com/meltir</a></li>
                <li class="fa-spotify"><a href="https://play.spotify.com/user/meltir" target="_blank">spotify.com/user/meltir</a></li>
                {% block sourcecode %}<li class="fa-code"><a href="https://github.com/meltir/2019.meltir.com/blob/master/src/Controller/HomeController.php" target="_blank">Page source</a></li>{% endblock %}
            </ul>
            <ul class="copyright">
                <li>&copy; www.meltir.com, All rights reserved.</li><li>Design: <a href="http://html5up.net" target="_blank">HTML5 UP</a></li>
            </ul>
        </div>
    </section>

</div>

<!-- Scripts -->
<script src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.scrollex.min.js') }}"></script>
<script src="{{ asset('assets/js/browser.min.js') }}"></script>
<script src="{{ asset('assets/js/breakpoints.min.js') }}"></script>
<script src="{{ asset('assets/js/util.js') }}"></script>
<script src="{{ asset('assets/js/main.js') }}"></script>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-1898734-1', 'auto');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');
</script>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/solidstate/wide-block-section.html.twig
<section class="wrapper spotlight {{ cycle(['','alt'],style_id) }} style{{ style_id }}">
    <div class="inner">
            {% if block.linkImage is not empty %}
                <a class="image"><img src="{{ asset(postimagepath ~ block.linkImage) }}" alt="{{ block.title }}" /></a>
            {% endif %}
        <div class="content">
            {% if block.title is defined %}
            <h2 class="major">{{ block.title }}</h2>
            {% endif %}
            <p>{{ block.body|raw }}</p>
            {% if block.linkUrl is not empty %}
            <a href="{{ block.linkUrl }}" class="special">{{ block.linkTitle }}</a>
            {% endif %}
        </div>
    </div>
</section>

templates/solidstate/wide-block.html.twig
{% set style_id=2 %}
{% for block in wideblocks %}
    {{  include('solidstate/wide-block-section.html.twig') }}
    {% set style_id = style_id+1 %}
    {% if style_id > 6 %}
        {% set style_id=1 %}
    {% endif %}
{% endfor %}